// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASN41jPodR8az4-eSxhAcBcJ06E-hwGsI',
    appId: '1:611746277242:web:d8c8315a37653fc34fd8c3',
    messagingSenderId: '611746277242',
    projectId: 'contactapp-3c263',
    authDomain: 'contactapp-3c263.firebaseapp.com',
    storageBucket: 'contactapp-3c263.appspot.com',
    measurementId: 'G-NMV0GG5EW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcpabkUaE1xBADjHVifk9M3vGE5LLzbQ',
    appId: '1:611746277242:android:056418f9c3a621e94fd8c3',
    messagingSenderId: '611746277242',
    projectId: 'contactapp-3c263',
    storageBucket: 'contactapp-3c263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpg0KOr5ixwzWGJjaZ0D1IcRGot2mZwIo',
    appId: '1:611746277242:ios:99f73a1af06e19524fd8c3',
    messagingSenderId: '611746277242',
    projectId: 'contactapp-3c263',
    storageBucket: 'contactapp-3c263.appspot.com',
    iosBundleId: 'com.example.labG2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpg0KOr5ixwzWGJjaZ0D1IcRGot2mZwIo',
    appId: '1:611746277242:ios:99f73a1af06e19524fd8c3',
    messagingSenderId: '611746277242',
    projectId: 'contactapp-3c263',
    storageBucket: 'contactapp-3c263.appspot.com',
    iosBundleId: 'com.example.labG2',
  );
}
